import { Category, StockItem, MoneyEntry, User } from '@/types';

export const mockUser: User = {
  id: '1',
  email: 'admin@fruitsveggies.com',
  name: 'Admin User',
  created_at: new Date().toISOString(),
};

export const mockCategories: Category[] = [
  {
    id: '1',
    name: 'Fruits',
    description: 'Fresh seasonal fruits',
    color: '#ef4444',
    user_id: '1',
    order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Vegetables',
    description: 'Farm fresh vegetables',
    color: '#22c55e',
    user_id: '1',
    order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Leafy Greens',
    description: 'Fresh leafy vegetables',
    color: '#16a34a',
    user_id: '1',
    order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Root Vegetables',
    description: 'Underground vegetables',
    color: '#a16207',
    user_id: '1',
    order: 4,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockStockItems: StockItem[] = [
  {
    id: '1',
    name: 'Apples',
    category_id: '1',
    quantity_brought: 100,
    quantity_sold: 75,
    price_per_unit: 2.5,
    entry_cost: 1.5,
    user_id: '1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Bananas',
    category_id: '1',
    quantity_brought: 200,
    quantity_sold: 180,
    price_per_unit: 1.2,
    entry_cost: 0.8,
    user_id: '1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Carrots',
    category_id: '2',
    quantity_brought: 150,
    quantity_sold: 120,
    price_per_unit: 1.8,
    entry_cost: 1.2,
    user_id: '1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Spinach',
    category_id: '3',
    quantity_brought: 80,
    quantity_sold: 65,
    price_per_unit: 3.0,
    entry_cost: 2.0,
    user_id: '1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Potatoes',
    category_id: '4',
    quantity_brought: 300,
    quantity_sold: 250,
    price_per_unit: 1.0,
    entry_cost: 0.6,
    user_id: '1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Tomatoes',
    category_id: '2',
    quantity_brought: 120,
    quantity_sold: 110,
    price_per_unit: 2.2,
    entry_cost: 1.4,
    user_id: '1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockMoneyEntries: MoneyEntry[] = [
  {
    id: '1',
    amount: 1000,
    type: 'entry',
    description: 'Initial investment',
    user_id: '1',
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    amount: 150,
    type: 'expense',
    description: 'Apple purchase',
    stock_item_id: '1',
    user_id: '1',
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    amount: 187.5,
    type: 'sale',
    description: 'Apple sales',
    stock_item_id: '1',
    user_id: '1',
    created_at: new Date().toISOString(),
  },
];